<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE en [
<!ELEMENT en (pair+)>
<!ELEMENT pair (key, value)>
<!ELEMENT key (#PCDATA)>
<!ELEMENT value (#PCDATA)>
]>
<en>
	<pair>
		<key>PLAY_OFFLINE</key>
		<value>play offline</value>
	</pair>
	<pair>
		<key>PLAY_ONLINE</key>
		<value>play online</value>
	</pair>
	<pair>
		<key>SETTINGS</key>
		<value>settings</value>
	</pair>
	<pair>
		<key>RULES</key>
		<value>rules</value>
	</pair>
	<pair>
		<key>EXIT</key>
		<value>exit</value>
	</pair>
	<pair>
		<key>MASTER</key>
		<value>master</value>
	</pair>
	<pair>
		<key>MUSIC</key>
		<value>music</value>
	</pair>
	<pair>
		<key>SFX</key>
		<value>SFX</value>
	</pair>
	<pair>
		<key>OK</key>
		<value>apply</value>
	</pair>
	<pair>
		<key>BACK</key>
		<value>back</value>
	</pair>
	<pair>
		<key>NEXT</key>
		<value>next</value>
	</pair>
	<pair>
		<key>PLAYER</key>
		<value>player</value>
	</pair>
	<pair>
		<key>READY</key>
		<value>ready</value>
	</pair>
	<pair>
		<key>PLAY</key>
		<value>play</value>
	</pair>
	<pair>
		<key>YES</key>
		<value>yes</value>
	</pair>
	<pair>
		<key>NO</key>
		<value>no</value>
	</pair>
	<pair>
		<key>ARE_YOU_SURE_WANT_TO_EXIT</key>
		<value>are you sure you want to exit?</value>
	</pair>
	<pair>
		<key>OPEN</key>
		<value>open</value>
	</pair>
	<pair>
		<key>CLOSED</key>
		<value>closed</value>
	</pair>
	<pair>
		<key>HUMAN</key>
		<value>human</value>
	</pair>
	<pair>
		<key>COMPUTER</key>
		<value>computer</value>
	</pair>
	<pair>
		<key>PASSIVE</key>
		<value>passive</value>
	</pair>
	<pair>
		<key>EASY</key>
		<value>easy</value>
	</pair>
	<pair>
		<key>MEDIUM</key>
		<value>medium</value>
	</pair>
	<pair>
		<key>HARD</key>
		<value>hard</value>
	</pair>
	<pair>
		<key>INSANE</key>
		<value>insane</value>
	</pair>
	<pair>
		<key>CHEATER</key>
		<value>cheater</value>
	</pair>



	<pair>
		<key>NEW_GAME</key>
		<value>new game</value>
	</pair>
	<pair>
		<key>LOAD_GAME</key>
		<value>load game</value>
	</pair>
	<pair>
		<key>SAVE_GAME</key>
		<value>save game</value>
	</pair>
	<pair>
		<key>HOST_GAME</key>
		<value>host game</value>
	</pair>
	<pair>
		<key>JOIN_GAME</key>
		<value>join game</value>
	</pair>
	<pair>
		<key>RANDOM_PLACEMENT</key>
		<value>random placement</value>
	</pair>
	<pair>
		<key>BACK_M</key>
		<value>back to main menu</value>
	</pair>
	
</en>